# Generated by Django 5.2.4 on 2025-07-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_audio_file_track_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='genre',
            field=models.CharField(choices=[('hiphop', 'Hip-Hop'), ('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('classical', 'Classical'), ('edm', 'EDM'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
