# Generated by Django 5.2.4 on 2025-07-20 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_userprofile_is_seller_alter_userprofile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='prefers_dark_mode',
        ),
    ]
