# Generated by Django 5.2.4 on 2025-07-20 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_purchase'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='purchased_at',
        ),
    ]
