# Generated by Django 5.2.4 on 2025-07-20 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_purchase_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
